version: '3.1'

services:
 
  db:
     container_name: servidor_mysql
     image: mariadb
     restart: always
     environment:
           MYSQL_DATABASE: db_drupal
           MYSQL_USER: user_drupal 
           MYSQL_PASSWORD: pass_drupal
           MYSQL_ROOT_PASSWORD: root
     volumes:
           - /opt/mysql:/var/lib/mysql

  drupal:
     container_name: drupal
     image: acabe10/drupal:v1
     restart: always
     ports:
         - 8080:80
     volumes:
         - /opt/drupal:/var/www/html/sites/
